project_django/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('todolist.urls'))
]

# TODO: Implement Routings Here

todolist/urls.py
from django.urls import path
from todolist.views import show_todolist, register, login_user, logout_user
from todolist.views import create_task, add_task, finish_task, unfinish_task, delete_task, delete_task_ajax, show_task, get_task_json, amogus, test, show_boardlist, add_board, get_board_json, show_board, invite_user

app_name = 'todolist'

urlpatterns = [
    path('', show_todolist, name='show_todolist'),
    path('board/', show_boardlist, name='show_boardlist'),
    path('register/', register, name='register'),
    path('login/', login_user, name='login'),
    path('logout/', logout_user, name='logout'),
    path('add/<int:board_id>', add_task, name='add_task'),
    path('add-board/', add_board, name='add_board'),
    path('create-task/', create_task, name='create_task'),
    path('finish-task/<int:task_id>', finish_task, name='finish_task'),
    path('unfinish-task/<int:task_id>', unfinish_task, name='unfinish_task'),
    path('delete-task/<int:task_id>', delete_task, name='delete_task'),
    path('delete/<int:task_id>', delete_task_ajax, name='delete_task_ajax'),
    path('show-task/<int:task_id>', show_task, name='show_task'),
    path('show-board/<int:board_id>', show_board, name='show_board'),
    path('json/', get_task_json, name='get_task_json'),
    path('json-board/', get_board_json, name='get_board_json'),
    path('amogus/', amogus, name='amogus'),
    path('test/<str:message>', test, name='test'),
    path('invite/', invite_user, name='invite_user'),
]

todolist/models.py
import imp
from django.db import models
from django.contrib.auth.models import User

class Board(models.Model):
    owner = models.ForeignKey(
        User,
        models.SET_NULL,
        blank=True,
        null=True,
        related_name='owner'
    )
    date = models.DateField()
    title = models.CharField(max_length=128)
    allowed_users = models.ManyToManyField(User, related_name='allowed_users')

class Task(models.Model):
    user = models.ForeignKey(
        User,
        models.SET_NULL,
        blank=True,
        null=True,
    )
    date = models.DateField()
    title = models.CharField(max_length=128)
    description = models.TextField()
    is_finished = models.BooleanField(default=False)
    board = models.ForeignKey(Board, on_delete=models.CASCADE, null=True)

todolist/forms.py
from django.forms import ModelForm, Form, CharField
from .models import Task, Board

class TaskForm(ModelForm):
    class Meta:
        model = Task
        fields = ['title', 'description']

class BoardForm(ModelForm):
    class Meta:
        model = Board
        fields = ['title']

class InviteUserForm(Form):
    invited_username = CharField(max_length=150)

todolist/views.py
from multiprocessing import context
from sqlite3 import Date
from django.shortcuts import render, redirect
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from django.core import serializers
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages
import datetime
from django.urls import reverse
from urllib3 import HTTPResponse
from .models import Task, Board
from .forms import TaskForm, BoardForm, InviteUserForm
from django.contrib.auth.models import User

@login_required(login_url='/login/')
def show_todolist(request):
    task_list = Task.objects.filter(user=request.user)

    context = {
        'username': request.user.username,
        'task_list': task_list,
    }

    return render(request, 'todolist.html', context)

@login_required(login_url='/login/')
def create_task(request):
    if request.method == 'POST':
        form = TaskForm(request.POST)
        if form.is_valid():
            new_task = form.save(commit=False)
            new_task.user = request.user
            new_task.date = datetime.datetime.now()
            new_task.save()
            form.save_m2m()
            return HttpResponseRedirect(reverse('todolist:show_boardlist'))
    else:
        form = TaskForm()
    return render(request, 'create_task.html', {'form': form})

@login_required(login_url='/login/')
def add_task(request, board_id):
    if request.method != 'POST':
        return redirect('todolist:amogus')
    
    form = TaskForm(request.POST)
    if form.is_valid():
        new_task = form.save(commit=False)
        new_task.user = request.user
        new_task.date = datetime.datetime.now()
        board = Board.objects.get(id=board_id)
        new_task.board = board
        new_task.save()
        form.save_m2m()
        return HttpResponse(serializers.serialize('json', [new_task, ]), content_type='application/json')

@login_required(login_url='/login/')
def finish_task(request, task_id):
    task = Task.objects.get(pk=task_id)

    if task.user == request.user:
        task.is_finished = True
        task.save()
    else:
        return redirect(reverse('todolist:amogus'))
    board_id = request.GET.get('board_id')
    return redirect(reverse('todolist:show_board', kwargs={'board_id': board_id}))

@login_required(login_url='/login/')
def unfinish_task(request, task_id):
    task = Task.objects.get(pk=task_id)

    if task.user == request.user:
        task.is_finished = False
        task.save()
    else:
        return redirect(reverse('todolist:amogus'))

    board_id = request.GET.get('board_id')
    return redirect(reverse('todolist:show_board', kwargs={'board_id': board_id}))

@login_required(login_url='/login/')
def delete_task(request, task_id):
    task = Task.objects.get(pk=task_id)

    if task.user == request.user:
        task.delete()
    else:
        return redirect(reverse('todolist:amogus'))

    board_id = request.GET.get('board_id')
    return redirect(reverse('todolist:show_board', kwargs={'board_id': board_id}))

@login_required(login_url='/login/')
def delete_task_ajax(request, task_id):
    task = Task.objects.get(pk=task_id)

    if task.user == request.user:
        task.delete()
    else:
        return redirect(reverse('todolist:amogus'))

    return HttpResponse(serializers.serialize('json', [task, ]), content_type='application/json')

def show_task(request, task_id):
    task = Task.objects.get(pk=task_id)

    return render(request, 'show_task.html', context={'task':task})

@login_required(login_url='/login/')
def get_task_json(request):
    board_id = request.GET.get('board_id')
    data = Task.objects.filter(board__id=board_id)
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")


# Board
@login_required(login_url='/login/')
def show_boardlist(request):
    board_list = Board.objects.filter(allowed_users=request.user)

    context = {
        'username': request.user.username,
        'board_list': board_list,
    }

    return render(request, 'boardlist.html', context)

@login_required(login_url='/login/')
def add_board(request):
    if request.method != 'POST':
        return redirect('todolist:amogus')
    
    form = BoardForm(request.POST)
    if form.is_valid():
        new_board = form.save(commit=False)
        new_board.owner = request.user
        new_board.date = datetime.datetime.now()
        new_board.save()
        new_board.allowed_users.add(new_board.owner)
        form.save_m2m()
        return HttpResponse(serializers.serialize('json', [new_board, ]), content_type='application/json')

@login_required(login_url='/login/')
def get_board_json(request):
    data = Board.objects.filter(allowed_users=request.user)
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

@login_required(login_url='/login/')
def show_board(request, board_id):
    board = Board.objects.get(pk=board_id)

    if not board.allowed_users.filter(id=request.user.id).exists():
        return redirect(reverse('todolist:amogus'))

    task_list = Task.objects.filter(board=board)

    context = {
        'username': request.user.username,
        'task_list': task_list,
        'board': board,
    }

    return render(request, 'todolist.html', context)

@login_required(login_url='/login/')
def invite_user(request):
    if request.method != 'POST':
        return redirect('todolist:amogus')
    
    form = InviteUserForm(request.POST)
    if form.is_valid():
        try:
            invited_username = form.cleaned_data["invited_username"]
            invited_user = User.objects.get(username=invited_username)
            
            board_id = request.POST.get('board_id')
            board = Board.objects.get(pk=board_id)
            board.allowed_users.add(invited_user)
            return JsonResponse({'success': True, 'messsage': 'User Invited'})
        except:
            return JsonResponse({'success': False, 'message': 'User Not Found'})

def register(request):
    form = UserCreationForm()

    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Akun telah berhasil dibuat!')
            return redirect('todolist:login')
    
    context = {'form':form}
    return render(request, 'register.html', context)

def login_user(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user) # melakukan login terlebih dahulu
            response = HttpResponseRedirect(reverse("todolist:show_boardlist")) # membuat response
            response.set_cookie('last_login', str(datetime.datetime.now())) # membuat cookie last_login dan menambahkannya ke dalam response
            return response
        else:
            messages.info(request, 'Username atau Password salah!')
    context = {}
    return render(request, 'login.html', context)

def logout_user(request):
    logout(request)
    response = HttpResponseRedirect(reverse('todolist:login'))
    response.delete_cookie('last_login')
    return redirect('todolist:login')

def amogus(request):
    return render(request, 'amogus.html')

def test(request, message):
    print(message)
    return redirect('todolist:show_boardlist')

todolist/templates/amogus.html
{% extends 'base.html' %}

{% block navbar %}
<div class="container-fluid">
    <a class="navbar-brand text-white" href="{% url 'todolist:show_boardlist' %}">Board List</a>
    <a class="btn btn-danger" href="{% url 'todolist:logout' %}">Logout</a>
</div>
{% endblock navbar %}

{% block content %}

{% load static %}

<h1>YOU ARE NOT ALLOWED</h1>

<img src="{% static 'amogus.gif' %}"><br>

<button><a href="{% url 'todolist:show_boardlist' %}">Return</a></button>
{% endblock content %}

todolist/templates/boardlist.html
{% extends 'base.html' %}

{% block navbar %}
<div class="container-fluid">
    <a class="navbar-brand text-white" href="{% url 'todolist:show_boardlist' %}">Boards List</a>
    <a class="btn btn-danger" href="{% url 'todolist:logout' %}">Logout</a>
</div>
{% endblock navbar %}

{% block meta %}
<script>
    $(document).ready(function(){
        $( "form#modal-form" ).submit(function( event ) {
            // alert( "Handler for .submit() called." );
            event.preventDefault();

            var actionurl = event.currentTarget.action;

            $.ajax({
                    url: actionurl,
                    type: 'post',
                    dataType: 'json',
                    data: $("form#modal-form").serialize(),
                    success: function(data) {
                        data.forEach(element => {
                            $("#boardlist-card-list").append(createBoardCard(element));
                        });
                    },
                    error: function(){
                        alert("ERROR");
                    }
            });
        });

        show_boards();
    });

    function show_boards() {
        $.get("../json-board", data => {
            data.forEach(element => {
                $("#boardlist-card-list").append(createBoardCard(element));
            });
        });
    }

    function createBoardCard(element) {
        var data = element.fields

        var card_div = $('<div></div>')
            .addClass('card todolist-card mt-2 mb-2')
            .attr('id', 'board-' + element.pk);

        var card_body = $('<div class="card-body"></div>')
            .append($('<h4 class="card-title"></h4>')
                .append(data.title)
                .append($('<span></span>')
                    .addClass('badge rounded-pill')))
            .append($('<h6 class="card-subtitle mb-2 text-muted">Created on: ' + data.date + '</h6>'))
            .append($('<a class="btn btn-secondary" href="../show-board/' + element.pk + '">Show board</a>'))
            // .append($('<a class="btn btn-danger" href="#">Delete task</a>')
            //     .click(() => {
            //         $.ajax({
            //             url: './delete/' + element.pk,
            //             type: 'delete',
            //             beforeSend: function(xhr) {
            //                 xhr.setRequestHeader("X-CSRFToken", getCookie("csrftoken"));
            //             },
            //             success: () => {
            //                 $('#task-' + element.pk).remove()
            //             }
            //         });
            //     }))
            ;
        
        return card_div.append(card_body);
    }

    function getCookie(name) {
        const value = `; ${document.cookie}`;
        const parts = value.split(`; ${name}=`);
        if (parts.length === 2) return parts.pop().split(';').shift();
    }
</script>
{% endblock meta %}

{% block content %}
<div class="todolist">

    <h1>Welcome, {{username}}</h1>

    <!-- <a class="btn btn-success mt-2 mb-2" href="{% url 'todolist:create_task' %}">Create a new task</a> -->

    <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#staticBackdrop">Add Board</button>

    <div id="boardlist-card-list" class="todolist-card-list">
    </div>
</div>

<!-- Modal -->
<div class="modal fade" id="staticBackdrop" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered modal-dialog-scrollable">
        <div class="modal-content">
            <div class="modal-header">
                <h1 class="modal-title fs-5" id="staticBackdropLabel">Add Board</h1>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <form method="POST" action="../add-board/" class="form-create-task" id="modal-form">
                    {% csrf_token %}
                    <!-- <label for="id_title">Title:</label> -->
                    <input type="text" name="title" placeholder="Title" maxlength="128" required="" id="id_title" class="form-control">
        
                    <!-- <label for="id_description">Description:</label> -->
                    <!-- <textarea name="description" placeholder="Description" cols="40" rows="10" required="" id="id_description" class="form-control"></textarea> -->
        
                    <input class="btn btn-primary mt-3" style="width: 100%;" type="submit" name="submit" value="Create" data-bs-dismiss="modal"/>
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-danger" data-bs-dismiss="modal">Cancel</button>
            </div>
        </div>
    </div>
</div>
  
{% endblock content %}

todolist/templates/create_task.html
{% extends 'base.html' %}

{% block meta %}
<title>New Task</title>
{% endblock meta %}

{% block navbar %}
<div class="container-fluid">
    <a class="navbar-brand text-white" href="{% url 'todolist:show_boardlist' %}">Board List</a>
    <a class="btn btn-danger" href="{% url 'todolist:logout' %}">Logout</a>
</div>
{% endblock navbar %}

{% block content %}  

<div class = "create-task container-fluid text-center mt-5">
    
    <h1>Create a New Task</h1>  

        <form method="POST" class="form-create-task">
            {% csrf_token %}
            <!-- <label for="id_title">Title:</label> -->
            <input type="text" name="title" placeholder="Title" maxlength="128" required="" id="id_title" class="form-control">

            <!-- <label for="id_description">Description:</label> -->
            <textarea name="description" placeholder="Description" cols="40" rows="10" required="" id="id_description" class="form-control"></textarea>

            <input class="btn btn-primary mt-3" style="width: 100%;" type="submit" name="submit" value="Create"/>
        </form>

</div>

{% endblock content %}

todolist/templates/login.html
{% extends 'base.html' %}

{% block meta %}
<title>Login</title>
{% endblock meta %}

{% block navbar %}
<div class="container-fluid">
    <a class="navbar-brand text-white" href="#">Task Management</a>
    <div class="d-flex justify-content-end">
        <a class="btn btn-outline-primary m-1" href="{% url 'todolist:login' %}">Login</a>
        <a class="btn btn-outline-primary m-1" href="{% url 'todolist:register' %}">Register</a>
    </div>
</div>
{% endblock navbar %}

{% block content %}

<div class = "login container-fluid text-center mt-5">

    <h1>Login</h1>

    <form method="POST" action="" class="form-signin">
        {% csrf_token %}
        <input type="text" name="username" placeholder="Username" class="form-control">
        <input type="password" name="password" placeholder="Password" class="form-control">

        <input class="btn btn-primary mt-3" type="submit" value="Login">
    </form>

    <div style="margin: 0 auto; max-width: 330px; width: 100%; padding: 0 15px;">
        {% if messages %}
            <ul>
                {% for message in messages %}
                    <li>{{ message }}</li>
                {% endfor %}
            </ul>
        {% endif %}
    </div>
        
    Belum mempunyai akun? <a href="{% url 'todolist:register' %}">Buat Akun</a>

</div>

{% endblock content %}

todolist/templates/register.html
{% extends 'base.html' %}

{% block meta %}
<title>Account Registration</title>
{% endblock meta %}

{% block navbar %}
<div class="container-fluid">
    <a class="navbar-brand text-white" href="#">Task Management</a>
    <div class="d-flex justify-content-end">
        <a class="btn btn-outline-primary m-1" href="{% url 'todolist:login' %}">Login</a>
        <a class="btn btn-outline-primary m-1" href="{% url 'todolist:register' %}">Register</a>
    </div>
</div>
{% endblock navbar %}

{% block content %}  

<div class = "register container-fluid text-center mt-5">
    
    <h1>Formulir Registrasi</h1>  

        <form method="POST" class="form-register">  
            {% csrf_token %}
            <!-- <label for="id_username" class="form-label">Username</label> -->
            <input type="text" name="username" placeholder="Username" maxlength="150" autocapitalize="none" autocomplete="username" autofocus="" required="" id="id_username" class="form-control">
            <!-- <label for="id_password1" class="form-label">Password</label> -->
            <input type="password" name="password1" placeholder="Password" autocomplete="new-password" required="" id="id_password1" class="form-control">
            <div class="form-text help-text">
                <ul>
                    <li>Your password can’t be too similar to your other personal information.</li>
                    <li>Your password must contain at least 8 characters.</li>
                    <li>Your password can’t be a commonly used password.</li>
                    <li>Your password can’t be entirely numeric.</li>
                </ul>
            </div>
            <!-- <label for="id_password2" class="form-label">Password confirmation</label> -->
            <input type="password" name="password2" placeholder="Confirm Password" autocomplete="new-password" required="" id="id_password2" class="form-control">
            <div class="form-text help-text">Enter the same password as before, for verification.</div>

            <ul>
                {% if form.errors %}
                    {% for field in form %}
                        {% for error in field.errors %}
                            <li><div class="form-text help-text text-red">{{ error|escape }}</div></li>
                        {% endfor %}
                    {% endfor %}
                    {% for error in form.non_field_errors %}
                        <li><div class="form-text help-text text-red">{{ error|escape }}</div></li>
                    {% endfor %}
                {% endif %}
            </ul>

            <input type="submit" name="submit" value="Register" class="btn btn-primary mt-3"/> 
        </form>

    {% if messages %}  
        <ul>   
            {% for message in messages %}  
                <li>{{ message }}</li>  
                {% endfor %}  
        </ul>   
    {% endif %}

</div>  

{% endblock content %}

todolist/templates/show_task.html
{% extends 'base.html' %}

{% block navbar %}
<div class="container-fluid">
    <a class="navbar-brand text-white" href="{% url 'todolist:show_boardlist' %}">Task</a>
    <a class="btn btn-danger" href="{% url 'todolist:logout' %}">Logout</a>
</div>
{% endblock navbar %}

{% block content %}
<div class="todolist">
    <div class="d-flex justify-content-between align-items-center">
        <h3>{{ task.title }}</h3>
        {% if task.is_finished %}
            <span class="badge rounded-pill bg-success">Finished</span>
        {% else %}
            <span class="badge rounded-pill bg-danger">Not Finished</span>
        {% endif %}
    </div>

    <p class="mb-5" style="color: gray;">{{ task.date }}</p>

    <h5>Description</h5>
    <p class="mb-5">{{ task.description }}</p>

    <button class="btn btn-primary"><a href="{% url 'todolist:show_board' board_id=task.board.id %}" class="text-white">Return</a></button>
</div>
{% endblock content %}

todolist/templates/todolist.html
{% extends 'base.html' %}

{% block navbar %}
<div class="container-fluid">
    <a class="navbar-brand text-white" href="{% url 'todolist:show_boardlist' %}">Tasks List</a>
    <a class="btn btn-danger" href="{% url 'todolist:logout' %}">Logout</a>
</div>
{% endblock navbar %}

{% block meta %}
<script>
    $(document).ready(function(){
        $( "form#modal-form" ).submit(function( event ) {
            // alert( "Handler for .submit() called." );
            event.preventDefault();

            var actionurl = event.currentTarget.action;
            $.ajax({
                    url: actionurl,
                    type: 'post',
                    dataType: 'json',
                    data: $("form#modal-form").serialize() + "&board_id={{board.id}}",
                    success: function(data) {
                        data.forEach(element => {
                            $("#todolist-card-list").append(createTaskCard(element));
                        });
                    },
                    error: function(){
                        alert("ERROR");
                    }
            });
        });

        $( "form#modal-form-invite" ).submit(function( event ) {
            // alert( "Handler for .submit() called." );
            event.preventDefault();
            console.log($("form#modal-form-invite").serialize())
            var actionurl = event.currentTarget.action;
            $.ajax({
                    url: actionurl,
                    type: 'post',
                    data: $("form#modal-form-invite").serialize() + "&board_id={{board.id}}",
                    success: function(data) {
                        alert(data['success'] ? "User Invited" : "User Not Found");
                    },
                    error: function(){
                        alert("Error");
                    }
            });
        });

        show_tasks();
    });

    function show_tasks() {
        $.get("../json?board_id={{board.id}}", data => {
            data.forEach(element => {
                $("#todolist-card-list").append(createTaskCard(element));
            });
        });
    }

    function createTaskCard(element) {
        var data = element.fields

        var card_div = $('<div></div>')
            .addClass('card todolist-card mt-2 mb-2')
            .addClass(data.is_finished ? 'border-success' : 'border-danger')
            .attr('id', 'task-' + element.pk);

        var card_body = $('<div class="card-body"></div>')
            .append($('<h4 class="card-title"></h4>')
                .append(data.title)
                .append($('<span></span>')
                    .addClass('badge rounded-pill mx-2')
                    .addClass(data.is_finished ? 'bg-success' : 'bg-danger')
                    .text(data.is_finished ? 'Finished' : 'Not Finished')))
            .append($('<h6 class="card-subtitle mb-2 text-muted">Created on: ' + data.date + '</h6>'))
            .append($('<p class="card-text">' + data.description + '</p>'))
            .append($('<a class="btn btn-secondary" href="../show-task/' + element.pk + '">Show task</a>'))
            .append($('<a class="btn btn-primary">Change status</a>')
                .attr('href', (data.is_finished ? '../unfinish-task/' : '../finish-task/') + element.pk + "?board_id={{board.id}}"))
            .append($('<a class="btn btn-danger" href="">Delete task</a>')
                .click(() => {
                    $.ajax({
                        url: '../delete/' + element.pk + "?board_id={{board.id}}",
                        type: 'delete',
                        beforeSend: function(xhr) {
                            xhr.setRequestHeader("X-CSRFToken", getCookie("csrftoken"));
                        },
                        success: () => {
                            $('#task-' + element.pk).remove()
                        }
                    });
                }));
        
        return card_div.append(card_body);
    }

    function getCookie(name) {
        const value = `; ${document.cookie}`;
        const parts = value.split(`; ${name}=`);
        if (parts.length === 2) return parts.pop().split(';').shift();
    }
</script>
{% endblock meta %}

{% block content %}
<div class="todolist">

    <h1>{{board.title}}</h1>

    <!-- <a class="btn btn-success mt-2 mb-2" href="{% url 'todolist:create_task' %}">Create a new task</a> -->

    <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#staticBackdrop">Add Task</button>

    <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#staticBackdropUser">Invite User</button>

    <div id="todolist-card-list" class="todolist-card-list">
    </div>
</div>

<!-- Modal -->
<div class="modal fade" id="staticBackdrop" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered modal-dialog-scrollable">
        <div class="modal-content">
            <div class="modal-header">
                <h1 class="modal-title fs-5" id="staticBackdropLabel">Add Task</h1>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <form method="POST" action="../add/{{board.id}}" class="form-create-task" id="modal-form">
                    {% csrf_token %}
                    <!-- <label for="id_title">Title:</label> -->
                    <input type="text" name="title" placeholder="Title" maxlength="128" required="" id="id_title" class="form-control">
        
                    <!-- <label for="id_description">Description:</label> -->
                    <textarea name="description" placeholder="Description" cols="40" rows="10" required="" id="id_description" class="form-control"></textarea>
        
                    <input class="btn btn-primary mt-3" style="width: 100%;" type="submit" name="submit" value="Create" data-bs-dismiss="modal"/>
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-danger" data-bs-dismiss="modal">Cancel</button>
            </div>
        </div>
    </div>
</div>

<div class="modal fade" id="staticBackdropUser" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered modal-dialog-scrollable">
        <div class="modal-content">
            <div class="modal-header">
                <h1 class="modal-title fs-5" id="staticBackdropLabel">Invite User</h1>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <form method="POST" action="../invite/" class="form-create-task" id="modal-form-invite">
                    {% csrf_token %}
                    <!-- <label for="id_title">Title:</label> -->
                    <input id="invited_username" type="text" name="invited_username" maxlength="150" required class="form-control" placeholder="Username">
                    <!-- <input type="text" name="title" placeholder="Title" maxlength="128" required="" id="id_title" class="form-control"> -->
        
                    <!-- <label for="id_description">Description:</label> -->
                    <!-- <textarea name="description" placeholder="Description" cols="40" rows="10" required="" id="id_description" class="form-control"></textarea> -->
        
                    <input class="btn btn-primary mt-3" style="width: 100%;" type="submit" name="submit" value="Invite" data-bs-dismiss="modal"/>
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-danger" data-bs-dismiss="modal">Cancel</button>
            </div>
        </div>
    </div>
</div>
  
{% endblock content %}